### ISSUE TITLE
GpsSourceEnum is not generic enough

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#145]
Many gps sources are not in GpsSourceEnum, e.g.:
- CenterPointRTX
- RangePointRTX
- Omnistar
- WAAS
- TerraStar
- ...

This could be solved by making the enum more generic:
- GpsSourceEnum.SBAS (Satellite Based Augmentation System)
- GpsSourceEnum.PPP (Precise Point Positioning)
- ...

Jason Roesbeke, jason.roesbeke@cnhind.com

**Comment by aferreyra** [comment]
- I agree with the idea of making the enum more generic.
- I also have the (strong) opinion that GPSSourceEnum needs to turn into an EnumeratedRepresentation instead of an enumeration; there will continue to be new GPSSources that someone will want to keep track of, and it will be convenient to have the capability to add them without having to put out a new version of the framework.

**Comment by JasonRoesbeke** [comment]
SBAS & PPP has been added to the enum. 
Will investigate if an EnumeratedRepresentation could solve the issue when there are new GPSSources.
