### ISSUE TITLE
Prescription class issues

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#146]
- How to add the creation time in a Prescription? There is no TimeScope list in a Prescription.
- Request to change the class name of RxRates to RxCellLookup (in RasterGridPrescription). See VectorPrescription: RxShapeLookup has similar working.

Jason Roesbeke, jason.roesbeke@cnhind.com

**Comment by knelson-farmbeltnorth** [comment]
I agree with that name change to RxCellLookup.  It is consistent with other naming and what we have today is confusing.   An RxRates and a list of RxRates called RxRate (even though it is a list).   It should be foreach RxRate in RxCellLookup.RxRates instead of foreach RxRate in RxRates.RxRate.

The timestamp on a prescription also appears to be an oversight in the framework.

**Comment by aferreyra** [comment]
1) I like the idea of adding a TImeScopes list to Prescription.
2) I also think we should add a PersonRoles list to Prescription. (e.g., to record who made it)
3) Regarding the RxRates idea, we originally did not call it RxCellLookup because RxRates was also used by RxShapeLookup (and is still that way in the data model). However, in the code it's implemented as  "public List<RxRate> Rates", thus making the point moot. Therefore, I agree with the proposed change (and we need to change the data model accordingly).
