### ISSUE TITLE
RepresentationValue in a Note object

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#149]
Why is property Note.Value' not of type RepresentationValue instead of EnumeratedValue? How do I add e.g. vrWindSpeed Value in a Note?

Jason Roesbeke, jason.roesbeke@cnhind.com

**Comment by aferreyra** [comment]
If the intent were to enable associating some kind of Observation value to the note, you would be 100% right.
HOWEVER, I'm fairly certain that the intent here was to implement something compatible with the ISO 11783 CodedComment (CCT) element. 
The mechanism for including unstructured, key-value pair data in a document (at least until we refine the Observations document) was meant to be the StampedMeteredValues, which include a representation value, and the Id of the source of that value, which was called a "meter" at the time. This may be broken, because meters were replaced with something else (WorkingData, if memory serves).

**Comment by JasonRoesbeke** [comment]
Closing this as this can be solved with Observations.
