### ISSUE TITLE
OperationData & OperationSummary id reference to Prescription

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#158]
OperationData contains an id reference to a WorkItemOperation and to a Prescription, but OperationSummary has only one to a WorkItemOperation, why?

Follow up Q: Why does the OperationData has an id reference to a prescription while WorkItemOperation has also an id reference to it?
When would you have only a reference to a prescription that has not been referred to a WorkItemOperation?

**Comment by aferreyra** [comment]
WorkItemOperation describes a planned operation. It needs a prescription to fill out the "what", "where", and "how much" aspects of the planned field operation.

OperationData describes what you actually did, and it seemed a good idea to reference the Prescription that was used (if there was one).

You could have a reference to a prescription in OperationData if the field operation was conducted without a work order. Since prescriptions can stand alone, it's possible to have them available on the controller and attach them to the operation at runtime. This use case was brought up by machinerry and retail folks in the early days of SPADE.

**Comment by JasonRoesbeke** [comment]
This can be closed for me to keep supporting the use case of a field operation that was conducted without a work order.
